name: angular-github-pages

on:
  push:
    branches: [ "main" ]

env:
  page_subpath: /better-arso-radar/
  artifact_name: github-pages-artifact

jobs:
  build:
    name: Angular build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ^24.15.0
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build -- --base-href ${{ env.page_subpath }} --deploy-url ${{ env.page_subpath }} --configuration production

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5
      with:
        name: ${{ env.artifact_name }}
        path: ./dist/browser/

  deploy:
    name: GitHub Pages deployment
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_name: ${{ env.artifact_name }}
